name: merge-forks

on:
  schedule:
    - cron: '0 0 * * *'

env:
  token: ${{ secrets.BOT_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 3d_armor
      run: ./merge.sh
      env:
        repo: 3d_armor
        branch: master

    - name: areas
      run: ./merge.sh
      env:
        repo: areas
        branch: master

    - name: auroras
      run: ./merge.sh
      env:
        repo: auroras
        branch: master

    - name: bones
      run: ./merge.sh
      env:
        repo: bones
        branch: master

    - name: choppy
      run: ./merge.sh
      env:
        repo: choppy
        branch: main

    - name: darkage
      run: ./merge.sh
      env:
        repo: darkage
        branch: master

    - name: default
      run: ./merge.sh
      env:
        repo: default
        branch: master

    - name: doors
      run: ./merge.sh
      env:
        repo: doors
        branch: master

    - name: ethereal
      run: ./merge.sh
      env:
        repo: ethereal
        branch: master

    - name: facade
      run: ./merge.sh
      env:
        repo: facade
        branch: master

    - name: greek
      run: ./merge.sh
      env:
        repo: greek
        branch: master

    - name: moreblocks
      run: ./merge.sh
      env:
        repo: moreblocks
        branch: master

    - name: moretrees
      run: ./merge.sh
      env:
        repo: moretrees
        branch: master

    - name: mymillwork
      run: ./merge.sh
      env:
        repo: mymillwork
        branch: master

    - name: pkarcs
      run: ./merge.sh
      env:
        repo: pkarcs
        branch: master

    - name: streets
      run: ./merge.sh
      env:
        repo: streets
        branch: main

    - name: unified_inventory
      run: ./merge.sh
      env:
        repo: unified_inventory
        branch: master

    - name: xban2
      run: ./merge.sh
      env:
        repo: xban2
        branch: master

    - name: xdecor
      run: ./merge.sh
      env:
        repo: xdecor-libre
        branch: master
