name: mirror

on:
  schedule:
    - cron: '0 0 * * *'

env:
  token: ${{ secrets.BOT_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: bike
      run: ./mirror.sh
      env:
        source_repo: https://gitlab.com/h2mm/bike.git
        github_repo: bike_mirror.git
        branch: master

    - name: ta_apiary
      run: ./mirror.sh
      env:
        source_repo: https://gitlab.com/lesya_minetest_mods/ta_apiary.git
        github_repo: ta_apiary.git
        branch: main
    
    - name: morelights_dim
      run: ./mirror.sh
      env:
        source_repo: https://invent.kde.org/davidhurka/doxy_morelights_dim.git
        github_repo: morelights_dim.git
        branch: master
